---
baseURL: "/"
languageCode: en-us
title: October Curls
module:
  imports:
  - path: github.com/themefisher/persian-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: exampleSite/static/images
      target: static/images
summaryLength: "10"
paginate: "6"
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
  logo: "/images/s-letter-logo.webp"
  home: Home
  layout: "1"
  description: This is meta description
  preloader: true
  search: true
  author: ''
  author_image: images/banner-img.png
  bio: PhD Candidate who loves to write among the many other things. The myriad life,
    flickering thoughts, and a million words. Trying to find meaning through words
    and silence, that slip away sometimes too soon.
  mobile: ''
  email: ''
  address: 'Chicago land '
  contact_form_action: ''
  google_analitycs_id: ''
  copyright: ''
  instafeed:
    enable: true
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
  - icon: ti-facebook
    URL: "#"
  - icon: ti-twitter-alt
    URL: "#"
  - icon: ti-linkedin
    URL: "#"
  - icon: ti-github
    URL: "#"
menu:
  main:
  - name: About
    URL: about
    weight: "2"
  - name: Contact
    URL: contact
    weight: "3"
